[project]
name = "user-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "termcolor>=3.3.0",
    "wandb>=0.23.1",
    "tqdm>=4.65.0",
]
