_wandb:
    value:
        cli_version: 0.23.1
        e:
            k76s7m1g4q9shqai6y8nlmeso40no7it:
                codePath: run_refusal_experiment.py
                codePathLocal: run_refusal_experiment.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "810008178688"
                        used: "640742879232"
                email: laurence.w.liang@gmail.com
                executable: C:\Users\laure\Projects\user-models\.venv\Scripts\python.exe
                git:
                    commit: daf7f06a07729c2ff37ecd9277ad159d01da78ae
                    remote: https://github.com/TheFloatingString/user-models.git
                host: DESKTOP-DTOHFQR
                memory:
                    total: "14879617024"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\laure\Projects\user-models\run_refusal_experiment.py
                python: CPython 3.12.7
                root: C:\Users\laure\Projects\user-models
                startedAt: "2026-01-02T19:37:51.795623Z"
                writerId: k76s7m1g4q9shqai6y8nlmeso40no7it
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 95
            "2":
                - 95
            "3":
                - 13
                - 16
            "4": 3.12.7
            "5": 0.23.1
            "8":
                - 2
                - 3
            "12": 0.23.1
            "13": windows-amd64
categories:
    value:
        - voter_registration
        - healthcare
        - taxes
conversation_types:
    value:
        - single_turn
        - multi_turn
        - esl_to_native
        - native_to_esl
experiment_type:
    value: refusal_rate_fluency
judge_model:
    value: openai/gpt-5-nano
num_personas:
    value: 42
target_model:
    value: google/gemma-2-9b-it:free
